# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := zbardecoder
DEFS_Debug := \
	'-DNODE_GYP_MODULE_NAME=zbardecoder' \
	'-DUSING_UV_SHARED=1' \
	'-DUSING_V8_SHARED=1' \
	'-DV8_DEPRECATION_WARNINGS=1' \
	'-DV8_DEPRECATION_WARNINGS' \
	'-DV8_IMMINENT_DEPRECATION_WARNINGS' \
	'-D_GLIBCXX_USE_CXX11_ABI=1' \
	'-D_LARGEFILE_SOURCE' \
	'-D_FILE_OFFSET_BITS=64' \
	'-D__STDC_FORMAT_MACROS' \
	'-DOPENSSL_NO_PINSHARED' \
	'-DOPENSSL_THREADS' \
	'-DNAPI_DISABLE_CPP_EXCEPTIONS' \
	'-DBUILDING_NODE_EXTENSION' \
	'-DDEBUG' \
	'-D_DEBUG' \
	'-DV8_ENABLE_CHECKS'

# Flags passed to all source files.
CFLAGS_Debug := \
	-fPIC \
	-pthread \
	-Wall \
	-Wextra \
	-Wno-unused-parameter \
	-m64 \
	-g \
	-O0

# Flags passed to only C files.
CFLAGS_C_Debug :=

# Flags passed to only C++ files.
CFLAGS_CC_Debug := \
	-fno-rtti \
	-std=gnu++14

INCS_Debug := \
	-I/root/.cache/node-gyp/16.13.0/include/node \
	-I/root/.cache/node-gyp/16.13.0/src \
	-I/root/.cache/node-gyp/16.13.0/deps/openssl/config \
	-I/root/.cache/node-gyp/16.13.0/deps/openssl/openssl/include \
	-I/root/.cache/node-gyp/16.13.0/deps/uv/include \
	-I/root/.cache/node-gyp/16.13.0/deps/zlib \
	-I/root/.cache/node-gyp/16.13.0/deps/v8/include \
	-I/test/node-zbardecoder/node_modules/node-addon-api \
	-I/test/node-zbardecoder/linux64/opencv3/include \
	-I/test/node-zbardecoder/linux64/zbar/include

DEFS_Release := \
	'-DNODE_GYP_MODULE_NAME=zbardecoder' \
	'-DUSING_UV_SHARED=1' \
	'-DUSING_V8_SHARED=1' \
	'-DV8_DEPRECATION_WARNINGS=1' \
	'-DV8_DEPRECATION_WARNINGS' \
	'-DV8_IMMINENT_DEPRECATION_WARNINGS' \
	'-D_GLIBCXX_USE_CXX11_ABI=1' \
	'-D_LARGEFILE_SOURCE' \
	'-D_FILE_OFFSET_BITS=64' \
	'-D__STDC_FORMAT_MACROS' \
	'-DOPENSSL_NO_PINSHARED' \
	'-DOPENSSL_THREADS' \
	'-DNAPI_DISABLE_CPP_EXCEPTIONS' \
	'-DBUILDING_NODE_EXTENSION'

# Flags passed to all source files.
CFLAGS_Release := \
	-fPIC \
	-pthread \
	-Wall \
	-Wextra \
	-Wno-unused-parameter \
	-m64 \
	-O3 \
	-fno-omit-frame-pointer

# Flags passed to only C files.
CFLAGS_C_Release :=

# Flags passed to only C++ files.
CFLAGS_CC_Release := \
	-fno-rtti \
	-std=gnu++14

INCS_Release := \
	-I/root/.cache/node-gyp/16.13.0/include/node \
	-I/root/.cache/node-gyp/16.13.0/src \
	-I/root/.cache/node-gyp/16.13.0/deps/openssl/config \
	-I/root/.cache/node-gyp/16.13.0/deps/openssl/openssl/include \
	-I/root/.cache/node-gyp/16.13.0/deps/uv/include \
	-I/root/.cache/node-gyp/16.13.0/deps/zlib \
	-I/root/.cache/node-gyp/16.13.0/deps/v8/include \
	-I/test/node-zbardecoder/node_modules/node-addon-api \
	-I/test/node-zbardecoder/linux64/opencv3/include \
	-I/test/node-zbardecoder/linux64/zbar/include

OBJS := \
	$(obj).target/$(TARGET)/src/decoder.o \
	$(obj).target/$(TARGET)/src/index.o

# Add to the list of files we specially track dependencies for.
all_deps += $(OBJS)

# CFLAGS et al overrides must be target-local.
# See "Target-specific Variable Values" in the GNU Make manual.
$(OBJS): TOOLSET := $(TOOLSET)
$(OBJS): GYP_CFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_C_$(BUILDTYPE))
$(OBJS): GYP_CXXFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_CC_$(BUILDTYPE))

# Suffix rules, putting all outputs into $(obj).

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(srcdir)/%.cpp FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

# Try building from generated source, too.

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj).$(TOOLSET)/%.cpp FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj)/%.cpp FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

# End of this set of suffix rules
### Rules for final target.
LDFLAGS_Debug := \
	-pthread \
	-rdynamic \
	-m64

LDFLAGS_Release := \
	-pthread \
	-rdynamic \
	-m64

LIBS := \
	/test/node-zbardecoder/linux64/zbar/lib/libzbar.so \
	/test/node-zbardecoder/linux64/opencv3/lib64/libopencv_core.so \
	/test/node-zbardecoder/linux64/opencv3/lib64/libopencv_imgcodecs.so \
	/test/node-zbardecoder/linux64/opencv3/lib64/libopencv_highgui.so \
	/test/node-zbardecoder/linux64/opencv3/lib64/libopencv_imgproc.so

$(obj).target/zbardecoder.node: GYP_LDFLAGS := $(LDFLAGS_$(BUILDTYPE))
$(obj).target/zbardecoder.node: LIBS := $(LIBS)
$(obj).target/zbardecoder.node: TOOLSET := $(TOOLSET)
$(obj).target/zbardecoder.node: $(OBJS) FORCE_DO_CMD
	$(call do_cmd,solink_module)

all_deps += $(obj).target/zbardecoder.node
# Add target alias
.PHONY: zbardecoder
zbardecoder: $(builddir)/zbardecoder.node

# Copy this to the executable output path.
$(builddir)/zbardecoder.node: TOOLSET := $(TOOLSET)
$(builddir)/zbardecoder.node: $(obj).target/zbardecoder.node FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += $(builddir)/zbardecoder.node
# Short alias for building this executable.
.PHONY: zbardecoder.node
zbardecoder.node: $(obj).target/zbardecoder.node $(builddir)/zbardecoder.node

# Add executable to "all" target.
.PHONY: all
all: $(builddir)/zbardecoder.node

